db.Restaurants.find()
db.Restaurants.find({}, {restaurant_id:1, name:1, borough:1, cuisine:1})
db.Restaurants.find({}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id:0})
db.Restaurants.find({}, {restaurant_id:1, name:1, borough:1, address:{zipcode:1}, _id:0})
db.Restaurants.find({borough:'Bronx'}, {})
db.Restaurants.find({borough:'Bronx'}, {}).limit(5)
db.Restaurants.find({borough:'Bronx'}, {}).skip(5).limit(5)
db.Restaurants.find({"grades.score":{$gt:90}})
